# Generated by Django 3.2 on 2023-05-05 17:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_video_upload_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='upload_time',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
