# Generated by Django 3.2 on 2023-05-05 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_video_upload_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='total_duration',
            field=models.CharField(default='', max_length=255),
        ),
    ]
