# Generated by Django 3.2 on 2023-05-05 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_video_upload_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uservideointermediate',
            name='isViewed',
            field=models.BooleanField(default=True),
        ),
    ]
