# Generated by Django 3.2 on 2023-05-06 00:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_alter_uservideointermediate_isviewed'),
        ('api', '0009_video_total_duration'),
    ]

    operations = [
    ]
