# Generated by Django 3.2 on 2023-05-06 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_subscription'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='isSubscribed',
            field=models.IntegerField(default=0),
        ),
    ]
